name: EKS-cicd

on:
  push:
    branches:
      - dev
  pull_request_target: 
    types:
      - closed

env: 
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

jobs:
  
  green-deployment:
    runs-on: self-hosted
    if:  startsWith(github.head_ref, 'dev')

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
      run: |
        docker build -t k8s-cicd-green ./app/ 
        docker tag k8s-cicd-green:latest 635261526007.dkr.ecr.ap-south-1.amazonaws.com/k8s-cicd-green:latest
        docker push 635261526007.dkr.ecr.ap-south-1.amazonaws.com/k8s-cicd-green:latest

    - name: Update K8s Green deployment
      run: |
        export CLR=green
        export PRT=30081
        envsubst < ./manifest.yml | kubectl apply -f -
        kubectl rollout restart deployment prod-green
  
  blue-deployment:
    runs-on: self-hosted
    if:  startsWith(github.head_ref, 'stage')

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
      run: |
        docker build -t k8s-cicd-blue ./app/ 
        docker tag k8s-cicd-blue:latest 635261526007.dkr.ecr.ap-south-1.amazonaws.com/k8s-cicd-blue:latest
        docker push 635261526007.dkr.ecr.ap-south-1.amazonaws.com/k8s-cicd-blue:latest

    - name: Update K8s blue deployment
      run: | 
        export CLR=blue
        export PRT=30080
        envsubst < ./manifest.yml | kubectl apply -f -
        kubectl rollout restart deployment prod-blue
